### ISSUE TITLE
Error while trying to run the app

### ISSUE THREAD

**Issue by fmsouza** [rfreebern/simple-twitter-bot#2]
I'm having the following error appearing lots of times in my console after I configured my config.js and started the application:

```
{ [Error: Missing required parameter: status.]
  message: 'Missing required parameter: status.',
  statusCode: 403,
  twitterReply: '{"errors":[{"code":170,"message":"Missing required parameter: status."}]}',
  code: 170,
  allErrors: [ { code: 170, message: 'Missing required parameter: status.' } ] }
```

**Comment by rfreebern** [comment]
Oh, thanks @fmsouza! I haven't used this in quite a while so I'd believe Twitter's API has changed. I'll try to dig in and fix it soon.

**Comment by fmsouza** [comment]
Hi @rfreebern! Thanks for our answer.
I discovered what caused my issue: I had cleaned the response return, so it couldn't tweet a blank message.
Maybe a good fix for this problem could be check if there is any response to send before trying to send the post.
